### ISSUE TITLE
Electrum XSH wallet on windows desktop is not connecting...Alternative server options?

### ISSUE THREAD

**Issue by DeepM1** [ShieldCoin/electrum-XSH#5]
Electrum XSH wallet on windows desktop is not connecting.  If changing servers is an answer, why don't you all provide a list of different server choices?  Dev team needs to get this working so that coin can grow in popularity.  Lack of information about how a user can help correct technical problems on their own is a big issue and disappointment.
Please provide suggestions for a fix.  Only one server option is currently available in the wallet: 188.266.178.216  50002  Thank you.

**Comment by karyelist** [comment]
My wallet not connected ip 188.266.178.216 50002

Pls Check bug.

**Comment by DeepM1** [comment]
This is what I found on the XSH reddit page https://www.reddit.com/r/SHIELDCOIN/comments/7p2x65/wallet_not_connecting/
ip server
 **104.131.33.106  50002 using SSL.**
     This worked to connect the Electrum wallet to the XSH server network!  It took a while, 2-3 hours to receive my coins, however.
    I've also commented on that Reddit thread about the need for the dev team to publish much more info for the user.  Check that comment out, if you like.

**Comment by karyelist** [comment]
thanks for help.
Perfect it is working.
